name: Main Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch: # Add this section
    inputs:
      trigger_manually:
        description: 'Trigger manually'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your existing build steps go here
