name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your existing build steps go here

      - name: Trigger Workflow in Second Repository
        run: gh repo dispatch --repo <owner>/<repo2> --event <custom-event-name>
        # Or use curl or other methods to dispatch the event
