name: Main Workflow 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your existing build steps go here

      - name: Trigger Workflow in Repository 2
        run: |
          gh api repos/sreeharsha-alluri/GitHub_Action_Repo2/dispatches \
              -X POST \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"event_type": "trigger_automatically"}'
